dist: bionic

language: c

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH=master
      os: windows
      install:
        - printenv
        - ls
        - ls /
        - choco install cygwin
        - setup.exe --wait --quiet-mode --packages  automake,autoconf,gcc-g++,make,libgmp-devel,wget,zlib-devel
      
    - env: GAPBRANCH=master

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
