name: RegisterPackageTNUMDemo
version: 0.2
date: 2018-09-14
description: |
    Demo for RegisterPackageTNUM functionality

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.9"

www: https://gap-packages.github.io/RegisterPackageTNUMDemo/
readme: README.md
packageinfo: https://gap-packages.github.io/RegisterPackageTNUMDemo/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/RegisterPackageTNUMDemo/releases/download/v0.2/RegisterPackageTNUMDemo-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PH18</span>]   <b class='BibAuthor'>Pfeiffer, M. and Horn, M.</b>,
     <i class='BibTitle'>RegisterPackageTNUMDemo, Demo for RegisterPackageTNUM functionality,
             Version 0.2</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/RegisterPackageTNUMDemo/">https://gap-packages.github.io/RegisterPackageTNUMDemo/</a></span>.
    </p>
    

bibtex: |
    @misc{ RegisterPackageTNUMDemo0.2,
      author =           {Pfeiffer, M. and Horn, M.},
      title =            {{RegisterPackageTNUMDemo}, Demo for RegisterPackageTNUM functionality, {V}ersion 0.2},
      month =            {Sep},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/RegisterPackageTNUMDemo/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{RegisterPackageTNUMDemo/}}},
      printedkey =       {PH18}
    }

