name: RegisterPackageTNUMDemo
version: "0.3"
license: "GPL-2.0-or-later"
date: 2025-02-13
description: |
    Demo for RegisterPackageTNUM functionality

authors:
    - name: Markus Pfeiffer
      url: https://www.morphism.de/~markusp
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

www: https://gap-packages.github.io/RegisterPackageTNUMDemo/
readme: README.md
packageinfo: https://gap-packages.github.io/RegisterPackageTNUMDemo/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/RegisterPackageTNUMDemo/releases/download/v0.3/RegisterPackageTNUMDemo-0.3.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PH25</span>]   <b class='BibAuthor'>Pfeiffer, M. and Horn, M.</b>,
     <i class='BibTitle'>RegisterPackageTNUMDemo, Demo for RegisterPackageTNUM functionality,
             Version 0.3</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/RegisterPackageTNUMDemo/">https://gap-packages.github.io/RegisterPackageTNUMDemo/</a></span>.
    </p>
    

bibtex: |
    @misc{ RegisterPackageTNUMDemo,
      author =           {Pfeiffer, M. and Horn, M.},
      title =            {{RegisterPackageTNUMDemo},          {Demo          for
                          RegisterPackageTNUM functionality}, {V}ersion 0.3},
      month =            {Feb},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/RegisterPackageTNUMDemo/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{RegisterPackageTNUMDemo/}}},
      printedkey =       {PH25}
    }

